### ISSUE TITLE
Efi

### ISSUE THREAD

**Issue by ExTeZil** [xuanhung1509/nvim#1]
Hi, can you help, I'm very need efi for dell latitude e5570🥹🥹🥹

**Comment by xuanhung1509** [comment]
I've made the repo private since I accidentally exposed my Serial number. I'm planning to rewrite the guide in another repo soon.
In the meantime, if you just want a prebuilt EFI, I suggest you try looking for [others](https://github.com/misa198/dell-latitude-5570-hackintosh), or (better) follow [the guide from Dortania](https://dortania.github.io/OpenCore-Install-Guide/) to create your own so you get a fundamental understanding.
